# ==============================
# Common configuration
# ==============================
server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always

spring.jackson.serialization.indent-output=true
spring.jackson.time-zone=UTC

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

logging.level.com.example.course_management_system=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Default profile used when none is specified
spring.profiles.default=h2
